import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers/providers";
import { Header } from "@/components/Header";
import { EmojiRain } from "@/components/EmojiRain";
import { Footer } from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <Header />
          <EmojiRain />
          <main className="flex-1">{children}</main>
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
